import { BodyHome } from "./Home/BodyHome";
export type { BodyHomeProps } from "./Home/BodyHome";
import { SearchFlight } from "./Flight/SearchFlight";
export type { SearchFlightProps } from "./Flight/SearchFlight";
import { ListFlight } from "./Flight/ListFlight";
export type { ListFlightProps } from "./Flight/ListFlight";
import { FilterCommit } from "./HotelCommit/FilterCommit";
export type { FilterCommitProps } from "./HotelCommit/FilterCommit";
import { ListCommit } from "./HotelCommit/ListCommit";
export type { ListCommitProps } from "./HotelCommit/ListCommit";
export { BodyHome, SearchFlight, ListFlight, FilterCommit, ListCommit };
